linters:
  phpcs:
    standard: CakePHP
    extensions: 'php,ctp'
    enabled: true
  csslint: {  }

fixers:
  enabled: true

files:
  ignore:
    - 'vendor/*'
    - 'bower_components/*'
    - 'node_modules/*'
